add PRYV_CONF_ROOT where it was missing and adapt fail if it's not present

diff --git a/pryv.io/cluster/restart-pryv b/pryv.io/cluster/restart-pryv
--- a/pryv.io/cluster/restart-pryv
+++ b/pryv.io/cluster/restart-pryv
@@ -3,8 +3,11 @@
 # stop
 docker-compose -f pryv/pryv.yml down
 
+# Direcory where application configuration files are supposed to be stored
+export PRYV_CONF_ROOT="/var/pryv"
+
 # run
-[[ -e pryv/pryv.yml ]] || { echo >&2 "The file ./pryv/pryv.yml was not found in current working directory."; exit 1; }
+[[ -e ${PRYV_CONF_ROOT}/pryv/pryv.yml ]] || { echo >&2 "The file ${PRYV_CONF_ROOT}/pryv/pryv.yml was not found."; exit 1; }
 
 # Host machine hostname, used by reporting and airbrake
 export HOSTNAME=$HOSTNAME
diff --git a/pryv.io/cluster/run-config-follower b/pryv.io/cluster/run-config-follower
--- a/pryv.io/cluster/run-config-follower
+++ b/pryv.io/cluster/run-config-follower
@@ -1,10 +1,11 @@
 #!/usr/bin/env bash
 
-[[ -e config-follower/config-follower.yml ]] || { echo >&2 "The file ./config-follower/config-follower.yml was not found in current working directory."; exit 1; }
-
-echo "Running Pryv/config-follower component."
-
 # Direcory where application configuration files are supposed to be stored
 export PRYV_CONF_ROOT="/var/pryv"
+
+# run
+[[ -e ${PRYV_CONF_ROOT}/config-follower/config-follower.yml ]] || { echo >&2 "The file ${PRYV_CONF_ROOT}/config-follower/config-follower.yml was not found."; exit 1; }
+
+echo "Running Pryv/config-follower component."
 
 docker-compose -f config-follower/config-follower.yml up -d
diff --git a/pryv.io/cluster/run-pryv b/pryv.io/cluster/run-pryv
--- a/pryv.io/cluster/run-pryv
+++ b/pryv.io/cluster/run-pryv
@@ -1,12 +1,13 @@
 #!/usr/bin/env bash
 
-[[ -e pryv/pryv.yml ]] || { echo >&2 "The file ./pryv/pryv.yml was not found in current working directory."; exit 1; }
+# Direcory where application configuration files are supposed to be stored
+export PRYV_CONF_ROOT="/var/pryv"
+
+# run
+[[ -e ${PRYV_CONF_ROOT}/pryv/pryv.yml ]] || { echo >&2 "The file ${PRYV_CONF_ROOT}/pryv/pryv.yml was not found."; exit 1; }
 
 # Host machine hostname, used by reporting and airbrake
 export HOSTNAME=$HOSTNAME
-
-# Direcory where application configuration files are supposed to be stored
-export PRYV_CONF_ROOT="/var/pryv"
 
 # Uncomment line below to disable contractual information reporting
 #export reporting_optOut="true"
diff --git a/pryv.io/single-node/restart-config-follower b/pryv.io/single-node/restart-config-follower
--- a/pryv.io/single-node/restart-config-follower
+++ b/pryv.io/single-node/restart-config-follower
@@ -3,8 +3,11 @@
 # stop
 docker-compose -f config-follower/config-follower.yml down
 
+# Direcory where application configuration files are supposed to be stored
+export PRYV_CONF_ROOT="/var/pryv"
+
 # run
-[[ -e config-follower/config-follower.yml ]] || { echo >&2 "The file ./config-follower/config-follower.yml was not found in current working directory."; exit 1; }
+[[ -e ${PRYV_CONF_ROOT}/config-follower/config-follower.yml ]] || { echo >&2 "The file ${PRYV_CONF_ROOT}/config-follower/config-follower.yml was not found."; exit 1; }
 
 echo "Running Pryv/config-follower component."
 
