Change error message.

diff --git a/pryv.io/cluster/run-config-follower b/pryv.io/cluster/run-config-follower
--- a/pryv.io/cluster/run-config-follower
+++ b/pryv.io/cluster/run-config-follower
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-[[ -e config-follower/config-follower.yml ]] || { echo >&2 "Please cd into the configuration directory before running this script."; exit 1; }
+[[ -e config-follower/config-follower.yml ]] || { echo >&2 "The file ./config-follower/config-follower.yml was not found in current working directory."; exit 1; }
 
 echo "Running Pryv/config-follower component."
 
diff --git a/pryv.io/cluster/run-pryv b/pryv.io/cluster/run-pryv
--- a/pryv.io/cluster/run-pryv
+++ b/pryv.io/cluster/run-pryv
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-[[ -e pryv/pryv.yml ]] || { echo >&2 "Please cd into the configuration directory before running this script."; exit 1; }
+[[ -e pryv/pryv.yml ]] || { echo >&2 "The file ./pryv/pryv.yml was not found in current working directory."; exit 1; }
 
 echo "Running Pryv/core component."
 docker-compose -f pryv/pryv.yml up -d
