finish fixing run, restart, stop scripts

diff --git a/pryv.io/cluster/stop-pryv b/pryv.io/cluster/stop-pryv
--- a/pryv.io/cluster/stop-pryv
+++ b/pryv.io/cluster/stop-pryv
@@ -1,1 +1,12 @@
-docker-compose -f pryv/pryv.yml down
+#!/usr/bin/env bash
+
+# Directory where application configuration files are supposed to be stored
+export PRYV_CONF_ROOT="/var/pryv"
+# Host machine hostname, used by reporting and airbrake
+export HOSTNAME=$HOSTNAME
+
+# check
+[[ -e ${PRYV_CONF_ROOT}/pryv/pryv.yml ]] || { echo >&2 "The file ${PRYV_CONF_ROOT}/pryv/pryv.yml was not found."; exit 1; }
+
+# stop
+docker-compose -f ${PRYV_CONF_ROOT}/pryv/pryv.yml down
