Unified run & restart scripts a bit

diff --git a/pryv.io/single-node/restart-config-leader b/pryv.io/single-node/restart-config-leader
--- a/pryv.io/single-node/restart-config-leader
+++ b/pryv.io/single-node/restart-config-leader
@@ -1,10 +1,14 @@
 #!/usr/bin/env bash
 
+# Directory where application configuration files are supposed to be stored
+export PRYV_CONF_ROOT="/var/pryv"
+
+# check
+[[ -e ${PRYV_CONF_ROOT}/config-leader/config-leader.yml ]] || { echo >&2 "The file ${PRYV_CONF_ROOT}/config-leader/config-leader.yml was not found."; exit 1; }
+
 # stop
-docker-compose -f config-leader/config-leader.yml down
+docker-compose -f ${PRYV_CONF_ROOT}/config-leader/config-leader.yml down
 
 # run
-[[ -e config-leader/config-leader.yml ]] || { echo >&2 "The file ./config-leader/config-leader.yml was not found in current working directory."; exit 1; }
-
 echo "Running Pryv/config-leader component."
-docker-compose -f config-leader/config-leader.yml up -d
+docker-compose -f ${PRYV_CONF_ROOT}/config-leader/config-leader.yml up -d
diff --git a/pryv.io/single-node/restart-pryv b/pryv.io/single-node/restart-pryv
--- a/pryv.io/single-node/restart-pryv
+++ b/pryv.io/single-node/restart-pryv
@@ -1,16 +1,16 @@
 #!/usr/bin/env bash
 
-# stop
-docker-compose -f pryv/pryv.yml down
-
-# Direcory where application configuration files are supposed to be stored
+# Directory where application configuration files are supposed to be stored
 export PRYV_CONF_ROOT="/var/pryv"
-
-# run
-[[ -e ${PRYV_CONF_ROOT}/pryv/pryv.yml ]] || { echo >&2 "The file ${PRYV_CONF_ROOT}/pryv/pryv.yml was not found."; exit 1; }
-
 # Host machine hostname, used by reporting and airbrake
 export HOSTNAME=$HOSTNAME
 
+# check
+[[ -e ${PRYV_CONF_ROOT}/pryv/pryv.yml ]] || { echo >&2 "The file ${PRYV_CONF_ROOT}/pryv/pryv.yml was not found."; exit 1; }
+
+# stop
+docker-compose -f ${PRYV_CONF_ROOT}/pryv/pryv.yml down
+
+# run
 echo "Running Pryv/core component."
-docker-compose -f pryv/pryv.yml up -d
+docker-compose -f ${PRYV_CONF_ROOT}/pryv/pryv.yml up -d
